CREATE DATABASE MESADINHA;
USE MESADINHA;

CREATE TABLE USUARIO(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
SEXO CHAR(1) NOT NULL,
EMAIL VARCHAR(150) NOT NULL,
ENDERECO VARCHAR(150) NOT NULL,
TELEFONE CHAR(15) NOT NULL,
SENHA VARCHAR(150) NOT NULL,
PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE CATEGORIA(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(100) NOT NULL,
PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE CONTA(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(100) NOT NULL,
TIPO VARCHAR(50) NOT NULL,
CATEGORIA_ID INT UNSIGNED NOT NULL,
USUARIO_ID INT UNSIGNED NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIA(ID),
FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID)
)ENGINE=INNODB;

CREATE TABLE LANCAMENTO(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
VALOR DOUBLE(9,2) NOT NULL,
DATA DATE NOT NULL,
CONTA_ID INT UNSIGNED NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(CONTA_ID) REFERENCES CONTA(ID)
)ENGINE=INNODB;